const Constant = {
	FETCH_ROUTE:"FETCH_ROUTE",
	CANCEL_FETCH: "CANCEL_FETCH",
	UPDATE_ROUTE: "UPDATE_ROUTE",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	UPDATE_START: "UPDATE_START",
	UPDATE_END: "UPDATE_END",
}

export default Constant